apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: embedding-dpl
spec:
  selector:
    matchLabels:
      app: embedding-dpl
  replicas: 1
  template:
    metadata:
      labels:
        app: embedding-dpl
    spec:
      containers:
      - name: embedding-dpl
        image: hush205/autocap-embedding-service:latest
        resources:
          requests:
            cpu: 200m
            memory: 3Gi
        env:
        - name: APP_NAME
          value: "Embedding Service"
        - name: VERSION
          value: "1.0.0"
        - name: CLIP_MODEL_DIR
          value: "/models/clip-roberta-finetuned"
---
