apiVersion: v1
kind: Service
metadata:
  name: embedding-svc
  labels:
    app: embedding-svc
spec:
  ports:
    - name: embedding
      protocol: "TCP"
      port: 80
      targetPort: 80
  selector:
    app: embedding-dpl