apiVersion: apps/v1
kind: Deployment
metadata:
  name: embedding-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: embedding
  template:
    metadata:
      labels:
        component: embedding
    spec:
      containers:
        - name: embedding
          image: hush205/autocap-embedding-service:latest
          resources:
            requests:
              cpu: 100m
              memory: 400Mi
            limits:
              cpu: 4000m
              memory: 4Gi
          ports:
            - containerPort: 80
            