apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
        - name: web
          image: hush205/autocap-web-interface:latest
          resources:
            requests:
              cpu: 100m
              memory: 400Mi
            limits:
              cpu: 1000m
              memory: 2000Mi
          ports:
            - containerPort: 3000
          env:
            - name: API_GATEWAY_BASE_URL
              value: "http://api-gateway-svc"